# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: maxtext
site_url: https://maxtext.readthedocs.io
repo_url: https://github.com/AI-Hypercomputer/maxtext
repo_name: AI-Hypercomputer/maxtext

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

docs_dir: docs

nav:
  - Home: index.md
  - API Reference: reference.md

plugins:
  - search
  - gen-files:
      scripts:
        - scripts/gen_ref_pages.py
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_if_no_docstring: false
            filters: ["!^_"]
            show_root_heading: true
            show_source: true
            show_signature_annotations: true
            separate_signature: true
            merge_init_into_class: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
